print("Please enter the folowing information so i can sell it for a profit\n")
firstname=input("First name:")
lastname=input("Last name:")
grade=input("Grade (9-12):")
studentid=input("Student id:")
login=input("Login:")
cgpa=input("CGPA:")
print("\n")

print("your information:")
print(f"    Login:{login}")
print(f"    ID: {studentid}")
print(f"    Name:{firstname} {lastname}")
print(f"    CGPA:{cgpa}")
print(f"    Grade:{grade}")
